from .animal import Animal
from .llama import Llama
from .goat import Goat
from .horse import Horse
from .pig import Pig
from .cow import Cow
from .stingray import StingRay
from .goldfish import Goldfish
from .catfish import Catfish
from .otter import Otter
from .shark import Shark
from .python import Python
from .crocodile import Crocodile
from .salamander import Salamander
from .anaconda import Anaconda
from .gecko import Gecko